/**
 * Build the MCP Apps widget into a single self-contained HTML document, emitted as a TS module the
 * Cloudflare Pages Function imports as a plain string.
 *
 * Runs the widget Vite build (React + the app's MuscleLoadPanel/BodyMap + Tailwind) and inlines the
 * emitted w.js + w.css into workers/functions/widgets/widgets.generated.ts — a gitignored build
 * artifact exporting `WIDGET_HTML`, served as the `ui://macromaxxing/widgets.html` MCP resource
 * (workers/functions/lib/mcp.ts). We emit a `.ts` module rather than a `.html` imported with Vite's
 * `?raw` because the Pages Functions bundler (esbuild, not Vite) doesn't understand `?raw`. Inlining
 * is required because MCP Apps' default CSP blocks external <script src> / <link>.
 *
 *   yarn generate:widget      # = node --experimental-transform-types scripts/build-widgets.ts
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'vite'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, '.widget-dist')
const outDir = join(root, 'workers/functions/widgets')
const out = join(outDir, 'widgets.generated.ts')

await build({ configFile: join(root, 'vite.widget.config.ts') })

const js = readFileSync(join(dist, 'w.js'), 'utf8')
const css = readFileSync(join(dist, 'w.css'), 'utf8')
rmSync(dist, { recursive: true, force: true })

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script type="module">${js.replaceAll('</script>', '<\\/script>')}</script>
</body>
</html>
`

mkdirSync(outDir, { recursive: true })
writeFileSync(
	out,
	`// AUTO-GENERATED by scripts/build-widgets.ts — do not edit. Regenerate: yarn generate:widget\n// Serves the ui://macromaxxing/widgets.html MCP Apps resource (see workers/functions/lib/mcp.ts).\nexport const WIDGET_HTML = ${JSON.stringify(html)}\n`
)

console.info(`✓ ${out.replace(`${root}/`, '')} — ${(Buffer.byteLength(html) / 1024).toFixed(0)} KiB`)
